### warning으로 처리할 지 error로 처리할 지 그 레벨을 설정할 수 있습니다.
disable_rule:
included:
excluded:
- MoodToday/Supporting Files/AppDelegate.swift

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly



#- warning, error 모두 있는 규칙 -#

### 한 줄로는 warning의 수준만 설정할 수 있습니다.
line_length: 110  # implicitly

### 배열을 사용해 warning과 error의 수준을 모두 설정할 수 있습니다.
type_body_length:
  - 300 # warning, implicitly
  - 400 # error, implicitly

file_length:
  warning: 500  # explicitly
  error: 1200  # explicitly
  
  
  
#- 네이밍 규칙 -#

### min_length 및 max_length에 대한 warning/error를 설정할 수 있습니다.
### 규칙에 제외되는 특수한 이름도 지정할 수 있습니다.
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
